name: PROD WORKFLOW
on:
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  Publish-Release:
    runs-on: ubuntu-latest
    steps:
      - name: New Release Publish
        id: new_publish
        uses: release-drafter/release-drafter@v5
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

  Deploy-EC2:
    needs: Publish-Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        id: config-aws-creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACC }}:role/${{ secrets.OIDC_ROLE }}
          aws-region: us-east-1
          role-session-name: beztCICDSession
          mask-aws-account-id: 'no'

      - name: AWS SSM Send-Command
        run: |
          aws ssm send-command --document-name "AWS-RunShellScript" --targets "Key=InstanceIds,Values=i-0ec48f7103d49b805" --parameters commands=["sudo systemctl restart pwa-api.service"]
